---
name: Update Repository Manifest

on:
  ## Run daily at 5 PM UTC
  schedule:
    - cron: '0 17 * * *'
  
  ## Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up PowerShell
        shell: pwsh
        run: |
          Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"
      
      - name: Run Update-RepoManifest script
        shell: pwsh
        run: |
          ./scripts/Update-RepoManifest.ps1 -Verbose
      
      - name: Check for changes
        id: check_changes
        shell: pwsh
        run: |
          $changes = git status --porcelain manifest.json

          if ($changes) {
            Write-Host "Changes detected in manifest.json"
            echo "has_changes=true" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "No changes in manifest.json"
            echo "has_changes=false" >> $env:GITHUB_OUTPUT
          }
      
      - name: Get current date
        id: date
        if: steps.check_changes.outputs.has_changes == 'true'
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          echo "date=$date" >> $env:GITHUB_OUTPUT
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update repository manifest'
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          branch: auto/update-manifest-${{ steps.date.outputs.date }}
          delete-branch: true
          title: 'chore: update repository manifest'
          body: |
            ## Automated Manifest Update
            
            This PR was automatically generated by the Update Repository Manifest workflow.
            
            ### Changes
            - Updated `manifest.json` with latest module information
            
            ### Details
            - Run date: ${{ steps.date.outputs.date }}
            - Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            This PR will be automatically merged if there are no conflicts.
          labels: |
            automated
            manifest
          draft: false
      
      - name: Wait for PR checks
        if: steps.check_changes.outputs.has_changes == 'true' && steps.create_pr.outputs.pull-request-number != ''
        shell: pwsh
        run: |
          Write-Host "Waiting 30 seconds for PR checks to initialize..."
          Start-Sleep -Seconds 30
      
      - name: Enable auto-merge
        if: steps.check_changes.outputs.has_changes == 'true' && steps.create_pr.outputs.pull-request-number != ''
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
        run: |
          Write-Host "Enabling auto-merge for PR #$env:PR_NUMBER"
          
          ## Enable auto-merge with squash strategy
          gh pr merge $env:PR_NUMBER --auto --squash --delete-branch
          
          Write-Host "Auto-merge enabled. PR will merge automatically when all checks pass."
      
      - name: Summary
        if: always()
        shell: pwsh
        run: |
          if ("${{ steps.check_changes.outputs.has_changes }}" -eq "true") {
            if ("${{ steps.create_pr.outputs.pull-request-number }}" -ne "") {
              Write-Host "PR #${{ steps.create_pr.outputs.pull-request-number }} created and auto-merge enabled"
              Write-Host "PR URL: ${{ steps.create_pr.outputs.pull-request-url }}"
            } else {
              Write-Host "Changes detected but PR creation failed or PR already exists"
            }
          } else {
            Write-Host "No changes to manifest.json - no PR needed"
          }
